### ISSUE TITLE
Contribute a Node.js Couchbase Starter Kit

### ISSUE THREAD

**Issue by hummusonrails** [couchbase-starter-kit/contributing-guide#3]
## Looking to participate in Hacktoberfest 2024? 👻 

Here's a fantastic way to contribute to Couchbase's open-source ecosystem by creating a Node.js Starter Kit!

Couchbase already has starter kits for frameworks like [Spring](https://github.com/couchbase-starter-kit/couchbase-spring-starter) and [Rails](https://github.com/couchbase-starter-kit/couchbase-rails-starter), but we're missing one for Node.js! This is where **YOU** can make a difference. Help us build a Node.js Couchbase starter kit to assist other developers, like yourself, in easily integrating Couchbase into their Node.js applications.

### What You’ll Do:

> **TL;DR:** Create a Node.js app showcasing Couchbase's core features, ensuring cross-platform compatibility, with a detailed README and tests. **The final outcome is a new GitHub repo in your account for the starter kit, plus a PR in this repo adding your project to the community contributions section.**

- Set up a basic Node.js app that connects to a Couchbase cluster.
- Use the Couchbase Node.js SDK to demonstrate key functionalities.
- Include a sample .env file with necessary environment variables for connecting to Couchbase.
- Create a README.md with setup instructions.
- Configure deployment support for Gitpod and GitHub Codespaces.
- Add a test that verifies the connection to Couchbase using GitHub Actions.

### Basic Requirements: 

Your Node.js starter kit should include:

- [ ] Connection to Couchbase: With both Couchbase Server and Capella support.
- [ ] Environment Variables: Use the existing template provided in the [samples directory](https://github.com/couchbase-starter-kit/contributing-guide/tree/main/samples) of this repository.
- [ ] Deployment Configurations: Provide setup for Gitpod and GitHub Codespaces.
- [ ] Testing: Add a simple test workflow to validate the connection to Couchbase.

### Resources:

[**READ THIS FIRST - Instructions for getting started**](https://github.com/couchbase-starter-kit/contributing-guide/blob/main/README.md)

- [Couchbase Node.js SDK](https://github.com/couchbase/couchnode)
- [Sample README for your project](https://github.com/couchbase-starter-kit/contributing-guide/blob/main/samples/README.md)
- [Hacktoberfest Details](https://hacktoberfest.com/)

### How To Get Started: 

Follow the [contribution instructions](https://github.com/couchbase-starter-kit/contributing-guide/blob/main/README.md), and submit a pull request using the new starter kit pull request template with a link to your Node.js starter kit.

Good luck on your adventure! ✨

**Comment by codercatdev** [comment]
Sweet! Let's make this PR happen 😀

**Comment by shivaylamba** [comment]
@codercatdev!!!!!!So good to see you here

**Comment by codercatdev** [comment]
Little light on time but added the Node.js starter for review. @hummusonrails
